name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸ“¯
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "ğŸ™Œ This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ  This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸŒ¿ This name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          make build
      - name: Run tests
        run: |
          make test
      - name: Build debian package
        run: |
          make build-deb
      - name: Store debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: counter-v2.0.0
          path: |
            counter-v2.0.0.deb
      - name: Unpack debian package
        run: |
          dpkg-deb -x counter-v2.0.0.deb counter
      - name: Lint debian package
        run: |
          -lintian counter-v2.0.0.deb